### ISSUE TITLE
Affix description in MIPS 101

### ISSUE THREAD

**Issue by Xandaros** [SnorreSelmer/stationeers_ic10#13]
In the [MIPS Programming 101](https://github.com/SnorreSelmer/stationeers_ic10/blob/main/mips-programming-101.md) document, the [Branch/set matrix](https://github.com/SnorreSelmer/stationeers_ic10/blob/main/mips-programming-101.md#branchset-matrix) lists prefixes and suffixes. One particular prefix listed is `b-al`, which is definitely not a prefix.

If we are sticking to the linguistic analogy, what that table describes as suffixes are probably closer to stems, while `b-`, `s-`, and `br-` are the prefixes, and `-al` the only suffix.

**Comment by SnorreSelmer** [comment]
I've created an update, can you verify that this is what you suggested?
